<a href="https://colab.research.google.com/github/gantapriyanka1325/Cryptography-and-Networking-Security/blob/main/program3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

3 Design single unit perception for classification of iris dataset without using predefined models

In [1]:
#Implementation of AND Gate
import numpy as np
import tensorflow as tf

# Example input data (4 samples, 2 features each)
X = tf.constant([[0.0, 0.0],
                 [0.0, 1.0],
                 [1.0, 0.0],
                 [1.0, 1.0]], dtype=tf.float32)

# Manually define weights and bias
W = tf.constant([[2.0],   # weight for feature 1
                 [2.0]],  # weight for feature 2
                dtype=tf.float32)
b = tf.constant([-3.0], dtype=tf.float32)  # bias



In [2]:
# Forward pass: z = XW + b
z = tf.matmul(X, W) + b

# Activation (step function or sigmoid)
y_step = tf.cast(z >= 0, tf.int32)# hard threshold (binary output)
y_sigmoid = tf.math.sigmoid(z) # soft probability

print("Inputs:\n", X.numpy())
print("Linear combination (z):\n", z.numpy())
print("Step output (Perceptron):\n", y_step.numpy())
print("Sigmoid output (probability):\n", y_sigmoid.numpy())



Inputs:
 [[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Linear combination (z):
 [[-3.]
 [-1.]
 [-1.]
 [ 1.]]
Step output (Perceptron):
 [[0]
 [0]
 [0]
 [1]]
Sigmoid output (probability):
 [[0.04742587]
 [0.26894143]
 [0.26894143]
 [0.7310586 ]]
